// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SistemaVentas.ETL.App.Models.dboSchema;


namespace SistemaVentas.ETL.App.Models.dboSchema;

public partial class Country
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }
}