// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SistemaVentas.ETL.App.Models.dboSchema;


namespace SistemaVentas.ETL.App.Models.dboSchema;

public partial class OrderDetail
{
    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public int? Quantity { get; set; }

    public decimal? TotalPrice { get; set; }
}