// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SistemaVentas.ETL.App.Models.dboSchema;


namespace SistemaVentas.ETL.App.Models.dboSchema;

public partial class OrderStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }
}